module.exports = [
  require('./help'),
  require('./addallrole'),
  require('./blr'),
  require('./check'),
  require('./config'),
  require('./msg'),
  require('./podium'),
  require('./rlm'),
  require('./stats'),
  require('./to'),
  require('./unto'),
  require('./untoall'),
  require('./vc'),
];
