const mongoose = require('mongoose');

const guildConfigSchema = new mongoose.Schema({
  guildId: { type: String, required: true, unique: true },
  /** Commandes utilisables par tout le monde sur ce serveur (clés du registre) */
  publicCommands: { type: [String], default: [] },
  embedColor: { type: Number, default: null },
  customPrefix: { type: String, default: null },
  mainPrefixStored: { type: String, default: null },
  muteRoleId: { type: String, default: null },
  modLogChannelId: { type: String, default: null },
  messageLogChannelId: { type: String, default: null },
  voiceLogChannelId: { type: String, default: null },
  boostLogChannelId: { type: String, default: null },
  roleLogChannelId: { type: String, default: null },
  autoconfigLogChannelId: { type: String, default: null },
  raidLogChannelId: { type: String, default: null },
  raidPingRoleId: { type: String, default: null },
  ticketCategoryId: { type: String, default: null },
  antiraidAntiBot: { type: Boolean, default: false },
  antiraidAntiWebhook: { type: Boolean, default: false },
  antiraidAntiChannel: { type: Boolean, default: false },
  antiraidAntiRole: { type: Boolean, default: false },
  antiraidAntiBan: { type: Boolean, default: false },
  antiraidAntiEveryone: { type: Boolean, default: false },
  antispamEnabled: { type: Boolean, default: false },
  antilinkEnabled: { type: Boolean, default: false },
  badwordsList: { type: [String], default: [] },
  defaultPunish: { type: String, default: 'timeout' },
  clearDefaultLimit: { type: Number, default: 10 },
  whitelistUserIds: { type: [String], default: [] },
  blacklistUserIds: { type: [String], default: [] },
  botOwnerUserIds: { type: [String], default: [] },
  customCommands: {
    type: [{ trigger: { type: String }, response: { type: String } }],
    default: [],
  },
  piconlyChannelIds: { type: [String], default: [] },
  welcomeChannelId: { type: String, default: null },
  leaveChannelId: { type: String, default: null },
  suggestionChannelId: { type: String, default: null },
  reportChannelId: { type: String, default: null },
  autopublishChannelIds: { type: [String], default: [] },
  boostLogAsEmbed: { type: Boolean, default: true },
  creationLimit: { type: Number, default: 0 },
  guildLang: { type: String, default: 'fr' },
  antiraidAntiUnban: { type: Boolean, default: false },
  antimassmentionEnabled: { type: Boolean, default: false },
  autoreactChannelEmoji: {
    type: [{ channelId: { type: String }, emoji: { type: String } }],
    default: [],
  },
});

module.exports = mongoose.model('GuildConfig', guildConfigSchema);
